input_dir: '../datasets/small/01'
output_dir: '../datasets/small/01-aug'
overwrite: true

limit: 10 # always > 0
keep_origin: false

# Color
gaussian_blur:
  prob: 0
  sigma_min: 0
  sigma_max: 2.0

linear_contrast:
  prob: 0
  alpha_min: 0.6
  alpha_max: 1.4

add_to_brightness:
  prob: 0
  min: -30
  max: 30

# Geometric 
rotate:
  prob: 0
  min_angle: 90
  max_angle: 90

flip_lr:
  prob: 0.5

crop:
  prob: 0
  min_ratio: 0.2
  max_ratio: 0.2

scale_x:
  prob: 1
  min_scale: 0.7
  max_scale: 1.3

scale_y:
  prob: 1
  min_scale: 0.7
  max_scale: 1.3

shear_x:
  prob: 1
  min_angle: -20
  max_angle: 20

shear_y:
  prob: 1
  min_angle: -20
  max_angle: 20

# TO BE CONTINUE