input_dir: '../datasets/00-small'
output_dir: '../datasets/03-small'
overwrite: true

limit: 64 # always > 0
keep_origin: true

# Color
gaussian_blur:
  prob: 0
  sigma_min: 0
  sigma_max: 2.0

linear_contrast:
  prob: 0
  alpha_min: 0.6
  alpha_max: 1.4

add_to_brightness:
  prob: 0
  min: -30
  max: 30

# Geometric 
crop:
  prob: 1
  min_ratio: 0.2
  max_ratio: 0.2

flip_horizontal:
  prob: 0.0

rotate:
  prob: 1
  min_angle: -90
  max_angle: 90



# TO BE CONTINUE